# Generated by Django 3.0.7 on 2020-06-29 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('progeress_check', models.CharField(blank=True, choices=[('DY', 'Daily'), ('WY', 'Weekly'), ('MY', 'Monthly'), ('YY', 'Yearly')], default=None, max_length=2, null=True)),
                ('progeress_check_time', models.TimeField(blank=True, null=True)),
                ('reminder_notification', models.CharField(blank=True, choices=[('DY', 'Daily'), ('WY', 'Weekly'), ('MY', 'Monthly'), ('YY', 'Yearly')], default=None, max_length=2, null=True)),
                ('reminder_notification_time', models.TimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('archive', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
