# Generated by Django 3.0.7 on 2020-06-30 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_goallog_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='archive',
            new_name='archived',
        ),
    ]
