# Generated by Django 3.0.7 on 2020-07-01 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_auto_20200630_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='goallog',
            name='duration_direct_input',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
