# Generated by Django 3.0.7 on 2020-07-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0005_goallog_duration_direct_input'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Total Goal duration in hours.', null=True),
        ),
        migrations.AlterField(
            model_name='goallog',
            name='duration_direct_input',
            field=models.PositiveIntegerField(blank=True, help_text='Direclty input duration in minutes.', null=True),
        ),
    ]
